### PR TITLE
fix: Update fwupd-dbus to support fetching JCAT files

### PR DESCRIPTION
**Pull request by mmstick**
Required by https://github.com/pop-os/fwupd/pull/4

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by bflanagin** [comment]
After updating the manager I'm still getting this error when trying to update. 

Screenshot from 2021-04-05 09-03-45

**Comment by jackpot51** [comment]
@mmstick do you have a device to test this with?

**Comment by mmstick** [comment]
I have a Logitech receiver to test with

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
@bflanagin can you take a look at this again? I believe that issue is now fixed

**Review by bflanagin — APPROVED** [review]
Working as expected.

**Pull request merged**
