### PR TITLE
Updated Dependencies + i18n Support

### PR DESCRIPTION
**Pull request by mmstick**
- Removed conditional compilation, since it unnecessary complicated the build process
- Updated all dependencies to the latest versions, including a newer fwupd-dbus that doesn't require reqwest
- Added support for translations

### CODE REVIEW

**Comment by mmstick** [comment]
I see. Will fix the translations.

**Comment by jacobgkau** [comment]
On `a574ea2`, the hyperlink now works, but the space after the first sentence is still missing.

**Comment by mmstick** [comment]
I see. Fixed the space

**Comment by jacobgkau** [comment]
The space is now showing up properly in the plugged-in view:
Screenshot from 2021-05-12 13-22-08

However, there's now a stray space at the beginning of the second paragraph in the unplugged view:
Screenshot from 2021-05-12 13-21-58

**Comment by jacobgkau** [comment]
I'd suggest pushing a single space after the first sentence, rather than doing it separately in the charging section and before the guide section. I'm going to try doing that and will push it if it works.

**Comment by mmstick** [comment]
Got it.

**Review by jacobgkau — APPROVED** [review]
Formatting is correct, tested a firmware update on a laptop and a Thelio-IO firmware update on a desktop.

**Pull request merged**
