### PR TITLE
fix: fwupd error for devices needing requests feature

### PR DESCRIPTION
**Pull request by mmstick**
fwupd now requires that clients upgrading devices that require user interaction to set the `REQUESTS` feature flag and handle the `DeviceRequest` signal received during the install of a device that needs this feature. System76 Launch is one of those devices.

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
This looks like it fixes the problem! I'm going to double-check on a Launch testing machine just to be certain though.

**Review by leviport — DISMISSED** [review]
Also looks good on the Launch testing stations! Unifying receivers are also still upgrading as expected, and my oryp6 still shows up as expected.

**Comment by leviport** [comment]
The Ubuntu build failures do give me pause, but I'll leave that up to the Engineers to handle.

**Comment by leviport** [comment]
Looks like @13r0ck found a different issue, so I unapproved. Hopefully this screenshot provides context. If not, I can gather more info tomorrow.

IMG_0192

**Comment by mmstick** [comment]
How to replicate would be useful. Seems to be an error from within the fwupd daemon, and I see that the USB device was disconnected. You can get more detailed logs from fwupd by stopping the service and running the daemon manually with `sudo /usr/libexec/fwupd/fwupd -v`.

**Review by jackpot51 — APPROVED** [review]

**Comment by 13r0ck** [comment]
Steps to reproduce were to try and update the firmware on any of the keyboards that production has. 

someone in QA can grab the detailed logs as I am not at the office yet

**Comment by leviport** [comment]
Could this be because the boards are likely flashed with a super old version of the firmware from the factory? Testing an older PCB shows me a very different-looking firmware version number from anything I can downgrade my Launch to with `fwupdmgr`. 

 
I'll try manually updating this PCB and seeing if this PR makes it work afterwards. If the only problem is in assembly, we can modify the process to manually flash them, then make sure they are up to date with the firmware-manager.

**Comment by mmstick** [comment]
I guess that's possible. I was only testing with the oldest version fwupdmgr can downgrade to

**Review by leviport — APPROVED** [review]
Not working on that ancient Launch firmware version was broken before this PR anyway, so I'm re-approving this. We'll just find a different way to handle those initial firmware updates during assembly.

**Pull request merged**
