### PR TITLE
Update rust toolchain and dependencies

### LINKED ISSUE #139: Fails to build on Arch Linux
The following error:

```
error: failed to load manifest for workspace member `/build/firmware-manager/src/firmware-manager-0.1.2/gtk`

Caused by:
  failed to read `/build/firmware-manager/src/firmware-manager-0.1.2/gtk/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
  
```
is caused by trying to install the packages from AUR on arch linux:
`firmware-manager`  and `firmware-manager-git`

Similarly the error occurs when cloning the repo and running `makpkg -srcif` as directed on https://support.system76.com/articles/system76-driver/.

### LINKED ISSUE #140: Cannot be built due to the crates' conflicting Rust toolchain version requirements
One of the crates requires a version greater than 1.64.0, while the rest require 1.61.0 and if built with >1.64.0, they fail to build with compile errors. Relevant output:

Right after git cloning:

```bash
$ make prefix=/usr
cargo run -p tools --bin desktop-entry  -- \
	--appid com.system76.FirmwareManager \
	--name "Firmware Manager" \
	--icon firmware-manager \
	--comment "Manage system and device firmware" \
	--keywords firmware \
	--keywords system76 \
	--keywords fwupd \
	--keywords lvfs \
	--categories System \
	--categories GTK \
	--binary com.system76.FirmwareManager \
	--prefix /usr \
	--startup-notify
error: package `colorchoice v1.0.0` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.61.0
make: *** [Makefile:79: target/com.system76.FirmwareManager.desktop] Error 101
```

After removing the toolchain requirement by deleting the `rust-toolchain` file:

```bash
$ make prefix=/usr
cargo run -p tools --bin desktop-entry  -- \
	--appid com.system76.FirmwareManager \
	--name "Firmware Manager" \
	--icon firmware-manager \
	--comment "Manage system and device firmware" \
	--keywords firmware \
	--keywords system76 \
	--keywords fwupd \
	--keywords lvfs \
	--categories System \
	--categories GTK \
	--binary com.system76.FirmwareManager \
	--prefix /usr \
	--startup-notify
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/desktop-entry --appid com.system76.FirmwareManager --name 'Firmware Manager' --icon firmware-manager --comment 'Manage system and device firmware' --keywords firmware --keywords system76 --keywords fwupd --keywords lvfs --categories System --categories GTK --binary com.system76.FirmwareManager --prefix /usr --startup-notify`
cargo build --manifest-path gtk/Cargo.toml --no-default-features --release
   Compiling glib v0.15.12
   Compiling zbus_names v2.5.0
   Compiling failure_derive v0.1.8
   Compiling memoffset v0.8.0
   Compiling tendril v0.2.4
   Compiling parking_lot v0.12.1
   Compiling dashmap v5.4.0
   Compiling phf v0.7.24
   Compiling console v0.15.5
   Compiling mio v0.7.14
   Compiling gtk v0.15.5
   Compiling clap_lex v0.4.1
   Compiling enum_derive v0.1.7
   Compiling ansi_term v0.12.1
   Compiling arc-swap v1.6.0
   Compiling hex-view v0.1.3
   Compiling vec_map v0.8.2
   Compiling cascade v1.0.1
   Compiling strsim v0.10.0
   Compiling strsim v0.8.0
   Compiling field-offset v0.3.5
   Compiling slotmap v1.0.6
   Compiling system76-firmware-daemon v0.1.0 (https://github.com/pop-os/system76-firmware#c3d53236)
   Compiling clap_builder v4.2.4
   Compiling gtk-sys v0.15.3
error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:216:16
    |
216 |             if self.ptr.get().get() > MAX_INLINE_TAG {
    |                ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:233:21
    |
233 |             let p = self.ptr.get().get();
    |                     ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:241:20
    |
241 |                 if (*header).refcount.decrement() == 1 {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:485:26
    |
485 |         let kind = match self.ptr.get().get() {
    |                          ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

   Compiling tokio-udev v0.8.0
error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:561:15
    |
561 |         match self.ptr.get().get() {
    |               ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:571:17
    |
571 |         let n = self.ptr.get().get();
    |                 ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:579:17
    |
579 |         let n = self.ptr.get().get();
    |                 ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:581:39
    |
581 |         (n > MAX_INLINE_TAG) && (n == other.ptr.get().get())
    |                                       ^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:587:12
    |
587 |         if self.ptr.get().get() <= MAX_INLINE_TAG {
    |            ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:588:13
    |
588 |             self.ptr.set(unsafe { NonZero::new(EMPTY_TAG) });
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:722:17
    |
722 | ...   if (self.ptr.get().get() > MAX_INLINE_TAG) && (other.ptr.get().ge...
    |           ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:722:60
    |
722 | ...   if (self.ptr.get().get() > MAX_INLINE_TAG) && (other.ptr.get().ge...
    |                                                      ^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:728:25
    |
728 |                     && (other.aux.get() == self.aux.get() + self.len)
    |                         ^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:728:44
    |
728 |                     && (other.aux.get() == self.aux.get() + self.len)
    |                                            ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:921:34
    |
921 |             Tendril::shared(buf, self.aux.get() + offset, length)
    |                                  ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:936:13
    |
936 |             self.aux.set(self.aux.get() + n);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:936:26
    |
936 |             self.aux.set(self.aux.get() + n);
    |                          ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:958:9
    |
958 |         (*self.header()).refcount.increment();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:963:17
    |
963 |         let p = self.ptr.get().get();
    |                 ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:966:29
    |
966 |             (*header).cap = self.aux.get();
    |                             ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:968:13
    |
968 |             self.ptr.set(NonZero::new(p | 1));
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:969:13
    |
969 |             self.aux.set(0);
    |             ^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:979:23
    |
979 |             let ptr = self.ptr.get().get();
    |                       ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:991:9
    |
991 |         self.ptr.set(NonZero::new(buf.ptr as usize));
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:992:9
    |
992 |         self.aux.set(buf.cap);
    |         ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
   --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:997:10
    |
997 |         (self.ptr.get().get() & !1) as *mut Header<A>
    |          ^^^^^^^^^^^^^^
    |
    = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
    = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1002:19
     |
1002 |         let ptr = self.ptr.get().get();
     |                   ^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1007:23
     |
1007 |             false => (self.aux.get(), 0),
     |                       ^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1006:37
     |
1006 |             true => ((*header).cap, self.aux.get()),
     |                                     ^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1027:46
     |
1027 | ...   ptr::copy_nonoverlapping(x.as_ptr(), &mut t.len as *mut u32 as *...
     |                                            ^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1065:19
     |
1065 |             match self.ptr.get().get() {
     |                   ^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1068:43
     |
1068 | ...   slice::from_raw_parts(&self.len as *const u32 as *const u8, n)
     |                             ^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1084:19
     |
1084 |             match self.ptr.get().get() {
     |                   ^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1087:47
     |
1087 | ...   slice::from_raw_parts_mut(&mut self.len as *mut u32 as *mut u8, n)
     |                                 ^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1381:16
     |
1381 |             && self.ptr.get().get() <= MAX_INLINE_TAG
     |                ^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> /home/alexispurslane/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.2.4/src/tendril.rs:1383:13
     |
1383 |             self.ptr.set(inline_tag(new_len))
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

For more information about this error, try `rustc --explain E0793`.
error: could not compile `tendril` due to 36 previous errors
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:70: target/release/firmware-manager-gtk] Error 101
```

### PR DESCRIPTION
**Pull request by mmstick**
I'll tag a new release when it's merged.

Closes #139 
Closes #140

### CODE REVIEW

**Comment by ahoneybun** [comment]
For #140 I'm still seeing the same issue from what I can tell when using firmware-manager-git.

**Comment by ahoneybun** [comment]
That looks like it fixed it!

**Comment by ahoneybun** [comment]
I am getting the OS Error 13 when trying to read the Thelio Io board but that is a different issue then this one.

**Review by 13r0ck — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Still rendering and functioning as expected, tested on lemp10.

**Pull request merged**
