### PR TITLE
 i18n(sr-Cyrl, sr): Add Serbian (Cyrillic and Latin) translation

### PR DESCRIPTION
**Pull request by AAnzel**
Updated translation and corrected locale names after the following failed pull request: [https://github.com/pop-os/firmware-manager/pull/135](https://github.com/pop-os/firmware-manager/pull/135).

### CODE REVIEW

**Comment by n3m0-22** [comment]
Are you seeing both the Cyrillic and Latin translations on your end? As it is right now no matter what I set the system to I only see the Latin. I was able to see the Cyrillic only after removing the `sr` directory renaming the `sr-Cyrl` to `sr` and then building. I have yet to be able to get both Cyrillic and Latin translations to work in the same build.

**Comment by AAnzel** [comment]
@n3m0-22, I do not, but I thought it was something on my end. I believe the **sr** directory is used as a default or a fallback language. One way to fix this would probably be to rename **sr** into **sr-Latn**. I am trying to figure out how to proceed and am open to suggestions. Could you also please tell me whether I should use the locale codes as defined here [https://manpages.ubuntu.com/manpages/bionic/man3/DateTime::Locale::Catalog.3pm.html](https://manpages.ubuntu.com/manpages/bionic/man3/DateTime::Locale::Catalog.3pm.html) or this page is deprecated?

**Comment by n3m0-22** [comment]
I would think that page is still good as there are subsections at the top for 22.04 and 22.10. I'll look into it and see if I can come up with a solution. Thanks for the info.

**Comment by n3m0-22** [comment]
The directory `sr-Cyrl` is fine as is. The directory `sr` needs to be changed to `sr-Latn`. That has both translations working on my end.

**Comment by AAnzel** [comment]
@n3m0-22, thanks a lot for figuring out the solution. I hope the last commit ([https://github.com/pop-os/firmware-manager/pull/136/commits/3140f9abc7eb09b363fcc5b793518bf22b68c362](https://github.com/pop-os/firmware-manager/pull/136/commits/3140f9abc7eb09b363fcc5b793518bf22b68c362)) solves the problem completely.

**Review by n3m0-22 — APPROVED** [review]
I am now seeing the new translations both Cyrillic and Latin. Looks good to me. Thank you for your contribution.

**Comment by AAnzel** [comment]
It is my pleasure. :)

**Review by mmstick — APPROVED** [review]

**Pull request merged**
