### PR TITLE
i18n(kr): Add Korean translation. Needs additional overviews

### PR DESCRIPTION
**Pull request by PolyPaul**
A rough translation of Korean. May require a review before ready for market use.

### CODE REVIEW

**Comment by jacobgkau** [comment]
Thank you for the translation! Similar to https://github.com/pop-os/popsicle/pull/150, the language code for Korean should be `ko` instead of `kr`.

**Comment by PolyPaul** [comment]
I just found some Error within these, I will correct them and rename them correctly when I find some extras time. Same with the one on Popsicle.

**Comment by PolyPaul** [comment]
I am very new to Git and Github, should I just change the folder name and recommit or should I make a new branch entirely?

**Comment by jacobgkau** [comment]
@PolyPaul You can recommit after making your corrections. If you make a second commit on top of the first one (`git add`, `git commit`, and `git push`), we will squash them together when merging anyway. If you amend your original commit and force-push your branch (`git add`, `git commit --amend`, and `git push -f`), it will show up as a single commit in this branch. Either way is fine.

Let us know if you have any other questions!

**Comment by PolyPaul** [comment]
I just finished the errors and renamed the folder to ko. Have I done this correctly or is there a problem?

**Pull request merged**
