### PR TITLE
improv: Add more to firmware update dialog message

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Review by ahoneybun — DISMISSED** [review]
LGTM thank you!

**Comment by jacobgkau** [comment]
Here's what this currently looks like on serw12 with AC power and battery power:

Screenshot from 2020-10-30 08-49-57

Screenshot from 2020-10-30 08-50-51

The sentence `On machines running Open Firmware, the system should then boot normally.` makes sense in the support article because it's immediately followed by a section about extra steps for machines running non-open firmware. In this case, the sentence is irrelevant (because I'm on a Serval with non-open firmware), and also leaves me wondering what's going to happen if the system's not going to boot normally.

The preceding sentence `After the system powers off, press the power button to turn it back on.` was also taken from the context of after the update in the article, but in this message it sounds like I'll need to press the power button before the update, which is incorrect-- the first reboot is just a reboot.

@ahoneybun Would the following wording be okay to add instead?

> After the firmware update is complete, it may be necessary to press the power button more than once. See https://support.system76.com/articles/system-firmware/ for more information.

That would remove questions for non-open firmware users while also giving them easy access to the extra instructions (and will also provide more details about the USB-C charging statement as well, since that's not accurate for Open EC machines such as lemp9.)

**Comment by ahoneybun** [comment]
@jacobgkau I'm sorry that wording would be fine for this case.

**Comment by jacobgkau** [comment]
I've got it looking like this right now. Plugged in:

Screenshot from 2021-02-11 16-47-55

Unplugged:

Screenshot from 2021-02-11 16-47-16

The hyperlink works for opening [this article](https://support.system76.com/articles/system-firmware/) in a default browser. Starting the update still works.

**Review by jacobgkau — APPROVED** [review]

**Comment by ahoneybun** [comment]
LGTM!

**Review by ahoneybun — APPROVED** [review]

**Pull request merged**
